### ISSUE TITLE
fists use bullet decal

### ISSUE THREAD

**Issue by sashiezzz** [Dustfade/mcv-game-issues#2]
fists (melee weapon) use bullet decals (which looks wrong) as well as using effects like sparks on metal and wood chips coming out

all the knives use a different decal instead of a bullet decal that is meant for the knife with effects disabled so i know its possible to switch this out with something else maybe some sort of small dent or something as well as disabling the effects

![image](https://github.com/Dustfade/mcv-game-issues/assets/46254645/4e777cce-c989-46e8-abc8-995ad083fdaf)

![imag1e](https://github.com/Dustfade/mcv-game-issues/assets/46254645/2232cd25-7406-4821-b833-7c5d57adc158)

![imag5e](https://github.com/Dustfade/mcv-game-issues/assets/46254645/409ab2aa-cc13-4c2c-bc3b-7412930d7212)

**Comment by woookieee000** [comment]
Super Human

**Comment by AlexEpisode** [comment]
Fixed for next update
