### ISSUE TITLE
fists use dynamic crosshair while the rest of the knives use a dot

### ISSUE THREAD

**Issue by sashiezzz** [Dustfade/mcv-game-issues#4]
### What did you do?

use the weapon fists

### What did you see happen?

the fists appear to have a dynamic crosshair (allow the usage of a crosshair) while the rest of the knives use a dot (and dont allow the usage of a crosshair)

![image](https://github.com/Dustfade/mcv-game-issues/assets/46254645/09371ba4-fec8-420b-8eea-573a88154127)

### What did you expect to see?

a dot like the rest of the knives instead of a dynamic crosshair (the fist have no recoil so its not needed)

![image](https://github.com/Dustfade/mcv-game-issues/assets/46254645/89fd931b-832e-4c1c-a584-09688235a574)

![image](https://github.com/Dustfade/mcv-game-issues/assets/46254645/3fcb401b-ef5c-4554-a302-4c2caee06ce4)

![image](https://github.com/Dustfade/mcv-game-issues/assets/46254645/d8ac06bf-2728-4f48-a7c1-72944c8c3c1a)

**Comment by AlexEpisode** [comment]
Fixed for next update
