### ISSUE TITLE
when china lake is fully emptied and reloaded it ejects a shell at last reloaded shell (thirdperson)

### ISSUE THREAD

**Issue by sashiezzz** [Dustfade/mcv-game-issues#5]
### What did you do?

emptied the china lake and then reload fully while in thirdperson

### What did you see happen?

the china lake ejected a shell at the last reload in thirdperson

https://streamable.com/r94mf9

### What did you expect to see?

the china lake not ejecting a shell in thirdperson as seen in firstperson

https://streamable.com/ta177a

**Comment by sashiezzz** [comment]
this is fixed marking it as closed

**Comment by AlexEpisode** [comment]
Fixed for next update
